<?php
global $_W;
$sql = "
drop table if exists " . tablename('ycs_fxshop_adv') . " ;
drop table if exists " . tablename('ycs_fxshop_carrier') . " ;
drop table if exists " . tablename('ycs_fxshop_category') . " ;
drop table if exists " . tablename('ycs_fxshop_commission_apply') . " ;
drop table if exists " . tablename('ycs_fxshop_commission_clickcount') . " ;
drop table if exists " . tablename('ycs_fxshop_commission_level') . " ;
drop table if exists " . tablename('ycs_fxshop_commission_log') . " ;
drop table if exists " . tablename('ycs_fxshop_commission_shop') . " ;
drop table if exists " . tablename('ycs_fxshop_designer') . " ;
drop table if exists " . tablename('ycs_fxshop_dispatch') . " ;
drop table if exists " . tablename('ycs_fxshop_express') . " ;
drop table if exists " . tablename('ycs_fxshop_feedback') . " ;
drop table if exists " . tablename('ycs_fxshop_goods') . "; 
drop table if exists " . tablename('ycs_fxshop_goods_comment') . " ;
drop table if exists " . tablename('ycs_fxshop_goods_option') . " ;
drop table if exists " . tablename('ycs_fxshop_goods_param') . " ;
drop table if exists " . tablename('ycs_fxshop_goods_spec') . " ;
drop table if exists " . tablename('ycs_fxshop_goods_spec_item') . " ;
drop table if exists " . tablename('ycs_fxshop_member') . " ;
drop table if exists " . tablename('ycs_fxshop_member_address') . " ;
drop table if exists " . tablename('ycs_fxshop_member_cart') . " ;
drop table if exists " . tablename('ycs_fxshop_member_favorite') . " ;
drop table if exists " . tablename('ycs_fxshop_member_group') . " ;
drop table if exists " . tablename('ycs_fxshop_member_history') . " ;
drop table if exists " . tablename('ycs_fxshop_member_level') . " ;
drop table if exists " . tablename('ycs_fxshop_member_log') . " ;
drop table if exists " . tablename('ycs_fxshop_member_message_template') . " ;
drop table if exists " . tablename('ycs_fxshop_notice') . " ;
drop table if exists " . tablename('ycs_fxshop_order') . " ;
drop table if exists " . tablename('ycs_fxshop_order_comment') . " ;
drop table if exists " . tablename('ycs_fxshop_order_goods') . " ;
drop table if exists " . tablename('ycs_fxshop_order_refund') . " ;
drop table if exists " . tablename('ycs_fxshop_perm_log') . " ;
drop table if exists " . tablename('ycs_fxshop_perm_plugin') . "; 
drop table if exists " . tablename('ycs_fxshop_perm_role') . " ;
drop table if exists " . tablename('ycs_fxshop_perm_user') . " ;
drop table if exists " . tablename('ycs_fxshop_plugin') . " ;
drop table if exists " . tablename('ycs_fxshop_poster') . " ;
drop table if exists " . tablename('ycs_fxshop_poster_log') . " ;
drop table if exists " . tablename('ycs_fxshop_poster_qr') . " ;
drop table if exists " . tablename('ycs_fxshop_poster_scan') . " ;
drop table if exists " . tablename('ycs_fxshop_saler') . " ;
drop table if exists " . tablename('ycs_fxshop_store') . " ;
drop table if exists " . tablename('ycs_fxshop_sysset') . " ;
drop table if exists " . tablename('ycs_fxshop_creditshop_adv') . " ;
drop table if exists " . tablename('ycs_fxshop_creditshop_category') . " ;
drop table if exists " . tablename('ycs_fxshop_creditshop_goods') . " ;
drop table if exists " . tablename('ycs_fxshop_creditshop_log') . " ;
drop table if exists " . tablename('ycs_fxshop_virtual_category') . " ;
drop table if exists " . tablename('ycs_fxshop_virtual_data') . " ;
drop table if exists " . tablename('ycs_fxshop_virtual_type') . " ;
drop table if exists " . tablename('ycs_fxshop_designer_menu') . " ;
";
pdo_query($sql);